name: Build step

on:
  schedule:
    - cron: '* * * * *'
  push:
    branches: [ "master" ]
  
    
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        
  build-and-push-docker-image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: set up Docker Buildx
        id: buildX
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Login to github packages
        uses: docker/login-action@v2
        with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.G_TOKEN }}
        
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: /
             Bujji369/sriram-web:${{ github.sha }}
             ghcr.io/Bujji369/sriram-web:${{ github.sha }}
             
          push: ${{ github.ref == 'refs/head/master' }}
        
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
          
  update-manifest-stage:
   runs-on: ubuntu-latest
   needs: ['build-and-push-docker-image']
   steps:
     - uses: actions/checkout@v3
       with:
         repository: Bujji369/sriram-web-infra
         ref: 'main'
         token: ${{ secrets.G_TOKEN }}
     - name: setup git config
       run: /
         git config --global user.email "medichirlabujji@gmail.com"
         git config --global user.name "Bujji369"
         echo ${{ github.sha }}
         sed -i "s#${{ githubactor }}.*#${{ github.actor }}/sriram-web:${{ github.sha }}#g" sample-webapp.yml
         git add -A
         git commit -am "update image for - ${{ github.sha }}"
     - run: echo ${{ github }}
     - run: git push origin master
            

    
