name: Build step

on:
  
  push:
    branches: [ "master" ]
  
    
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        
  build-and-push-docker-image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
          
  update-manifest-stage:
   runs-on: ubuntu-latest
   needs: ['build-and-push-docker-image']
   steps:
     - uses: actions/checkout@v3
       with:
         repository: Bujji369/sriram-web-infra
         ref: 'master'
         token: ${{ secrets.G_TOKEN }}
     - name: setup git config
       run: |
         git config --global user.email "medichirlabujji@gmail.com"
         git config --global user.name "Bujji369"
         echo ${{ github.sha }}
         sed -i "s#${{ github.actor }}.*#${{ github.actor }}/sriram-web:${{ github.sha }}#g" sample-webapp.yml
         git add -A
         git commit -am "update image for - ${{ github.sha }}"
     - run: echo ${{ github }}
     - run: git push -u origin master
            

    
